#!/bin/ash

set -eo pipefail

BIN="/factorio/bin/x64/factorio"

if [[ ! -e "${SAVE_FILE}" ]]; then
  "$BIN" --create "${SAVE_FILE}"
fi

"$BIN" --start-server "${SAVE_FILE}" --server-settings "${CONFIG_FILE}"

